### ISSUE TITLE
Unable to compile libigl with AntTweakBar

### ISSUE THREAD

**Issue by ruoqingsun** [alecjacobson/FAST#1]
I am try to use the command "make -f Makefile.static" as the manual said to include AntTweakerBar into libigl. It seems not working for me. I got the following return.
```shell
make: Makefile.static: No such file or directory
make: *** No rule to make target `Makefile.static'.  Stop.
```
Later I also tried "make -f Makefile". The system is not able to include X11. Could you provide any help to this issue? 
![image](https://cloud.githubusercontent.com/assets/4344440/20923816/958ed0e0-bbae-11e6-9158-b2b007e045de.png)

**Comment by alecjacobson** [comment]
Are you on mac or linux? If you're on linux, it looks like you'll need to
install X11

**Comment by ruoqingsun** [comment]
I am currently on mac with MacOS Sierra version 10.12.1

**Comment by alecjacobson** [comment]
Oh, then use the osx makefiles

**Comment by ruoqingsun** [comment]
I have installed XQuartz in my system and go on trying to compile the AntTweakBar in project Libigl with command "make -f Makefile".

Here are two other problems come to me and I have fixed.
![image](https://cloud.githubusercontent.com/assets/4344440/20942410/92c6962a-bbfb-11e6-9427-f3dab2f9205e.png)
![image](https://cloud.githubusercontent.com/assets/4344440/20942429/a8e7094e-bbfb-11e6-8888-278aee3f46a4.png)

MacOS donent's have  "gcc -soname" and library "-lGL". Instead, "gcc -install_name" and "-framework OpenGL" seem correct.

But I came up with another problem when I running the make file:

```shell
Ruoqings-Air:src ruoqingsun$ gcc  -shared -Wl,-install_name,libAntTweakBar.so.1 -o ../lib/libAntTweakBar.so TwColors.o TwFonts.o TwOpenGL.o TwOpenGLCore.o TwBar.o TwMgr.o TwPrecomp.o LoadOGL.o LoadOGLCore.o TwEventGLFW.o TwEventGLUT.o TwEventSDL.o TwEventSDL12.o TwEventSDL13.o TwEventSFML.o TwEventX11.o -framework OpenGL -lstdc++
Undefined symbols for architecture x86_64:
  "_XAllocNamedColor", referenced from:
      CTwMgr::PixmapCursor(int) in TwMgr.o
  "_XCreateBitmapFromData", referenced from:
      CTwMgr::PixmapCursor(int) in TwMgr.o
  "_XCreateFontCursor", referenced from:
      CTwMgr::CreateCursors() in TwMgr.o
  "_XCreatePixmapCursor", referenced from:
      CTwMgr::PixmapCursor(int) in TwMgr.o
  "_XDefineCursor", referenced from:
      CTwMgr::SetCursor(unsigned long) in TwMgr.o
  "_XFetchBytes", referenced from:
      CTwBar::EditInPlaceGetClipboard(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in TwBar.o
  "_XFlush", referenced from:
      CTwMgr::FreeCursors() in TwMgr.o
      CTwMgr::CreateCursors() in TwMgr.o
      CTwMgr::PixmapCursor(int) in TwMgr.o
      CTwMgr::SetCursor(unsigned long) in TwMgr.o
  "_XFree", referenced from:
      CTwBar::EditInPlaceGetClipboard(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in TwBar.o
  "_XFreeCursor", referenced from:
      CTwMgr::FreeCursors() in TwMgr.o
  "_XFreePixmap", referenced from:
      CTwMgr::PixmapCursor(int) in TwMgr.o
  "_XLookupString", referenced from:
      _TwEventX11 in TwEventX11.o
  "_XSetErrorHandler", referenced from:
      CTwMgr::FreeCursors() in TwMgr.o
      CTwMgr::CreateCursors() in TwMgr.o
      CTwMgr::PixmapCursor(int) in TwMgr.o
      CTwMgr::SetCursor(unsigned long) in TwMgr.o
  "_XSetSelectionOwner", referenced from:
      CTwBar::EditInPlaceSetClipboard(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in TwBar.o
  "_XStoreBytes", referenced from:
      CTwBar::EditInPlaceSetClipboard(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in TwBar.o
  "_XSync", referenced from:
      CTwMgr::FreeCursors() in TwMgr.o
      CTwMgr::CreateCursors() in TwMgr.o
      CTwMgr::PixmapCursor(int) in TwMgr.o
      CTwMgr::SetCursor(unsigned long) in TwMgr.o
  "_glXGetCurrentDisplay", referenced from:
      CTwMgr::FreeCursors() in TwMgr.o
      _TwDraw in TwMgr.o
      CTwMgr::CreateCursors() in TwMgr.o
      CTwMgr::PixmapCursor(int) in TwMgr.o
      CTwMgr::SetCursor(unsigned long) in TwMgr.o
  "_glXGetCurrentDrawable", referenced from:
      _TwDraw in TwMgr.o
      CTwMgr::SetCursor(unsigned long) in TwMgr.o
  "_glXGetProcAddressARB", referenced from:
      LoadOpenGL() in LoadOGL.o
      LoadOpenGLCore() in LoadOGLCore.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
Is there any library that I missed?

**Comment by ruoqingsun** [comment]
I understand what you mean. I should use the following command
```shell
make -f makefile.osx
```

Thanks

**Comment by ruoqingsun** [comment]
I have recompiled the libigl add the lib files into usr/local/lib/libigl/lib folder. When I open the Xcode project of Skinning, I found the following problems.
![image](https://cloud.githubusercontent.com/assets/4344440/20948176/0158dea6-bc13-11e6-854d-4194dd66645e.png)
Where is the library liglmosek? I have installed the mosek vserion 7 into my computer and the compilation procedure of libigl showed that I have successfully install this package. But I could not find the library file liglmosk anywhere in libigl.
![image](https://cloud.githubusercontent.com/assets/4344440/20948226/54cada94-bc13-11e6-8bdf-7b72f17401e7.png)

**Comment by ruoqingsun** [comment]
I want to compile the whole libigl project to generate all the lib files.

```shell
mkdir -p lib
cd lib
cmake -DCMAKE_BUILD_TYPE=Release ../optional
make
```
Then I can generate a bunch of libraries in the lib folder. But the file libiglbbw.a is missing. Should I add any line in the makefile to let libigl to generate the libiglbbw.a ?
![image](https://cloud.githubusercontent.com/assets/4344440/20967900/d69764c0-bc81-11e6-92ee-b35593cfcef8.png)

I think the probable reason is that Libigl perhaps have some updates about bbw but corresponding modification hasn't been done here (as there is no extra directory in libigl regarding bbw). Could you please somehow update related codes?

![image](https://cloud.githubusercontent.com/assets/4344440/20969559/d03a8c30-bc89-11e6-977c-363289ab8ed4.png)

**Comment by alecjacobson** [comment]
There's a mismatch between the current libigl (12-07-16) and the libigl that this FAST repo is expecting (05-2016). I'm going to make libigl a submodule to freeze which commit of libigl is expected to get this to compile. Stay tuned.

**Comment by ruoqingsun** [comment]
Great. It would be appreciated if you can inform me here when the submodule is done. Thanks a lot!

**Comment by alecjacobson** [comment]
Should be working now. At least on mac osx. Please re-clone with the
--recursive option.

**Comment by ruoqingsun** [comment]
It works!!!Thanks for your effort 👍 👍 👍
