### ISSUE TITLE
Cannot find the implementation Skinning::initialize_transformations()

### ISSUE THREAD

**Issue by ruoqingsun** [alecjacobson/FAST#3]
Hello Alec,

I am currently reading the code of this FAST project and have encountered a problem. In the header file Skinning.h, there is a declaration of the function initialize_transformations()
```c++
// Initialize transformations for each handle to Identity
    bool initialize_transformations();
```
But there is no implementation of this function in Skinning.cpp. Maybe you can help me with this small issue. Thanks.

**Comment by alecjacobson** [comment]
Isn't there? See around line 3321 of Skinning.cpp.

**Comment by ruoqingsun** [comment]
Ah, I think I accidentally remove some parts of the code in my local file. I will sync again. :)
